services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower-global
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_DISCORD_URL}
