services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    ports:
      - "8088:80"
    volumes:
      - ./data/files:/srv
      - ./data/config/filebrowser.db:/database/filebrowser.db
    restart: unless-stopped
